### ISSUE TITLE
Please make the plugin multilanguage

### ISSUE THREAD

**Issue by pcav** [milieuinfo/Spatial-Subset-Query-Tool#2]
So it will be easier to use for all. See some recent plugin for guidance, if necessary. It should be an easy task.

**Comment by warrieka** [comment]
It's already in dutch and english, what other languages do you want?

**Comment by pcav** [comment]
en+nl is perfectly fine. My issue is that apparently the default is nl, so in my it box it appears nl rather than en, as expected.
